# -*- coding: utf-8 -*-
"""streamlit2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1shO92uUQrrLOIZ5jRJSjmyTY4Ah8rROx
"""

import streamlit as st

st.title("Hello World")
st.write("Welcome to Prediksi Penjualan Komputer dengan SVM")
