# -*- coding: utf-8 -*-
"""SVR Penjualan Komputer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BLWQb9zbj4PeAgs7qALftmH8minhq10n
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV, KFold, train_test_split
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

# 1. MEMUAT DATASET
try:
    df = pd.read_csv('SuperStore_Sales_Dataset.csv')
    print("Dataset berhasil dimuat.")
except FileNotFoundError:
    print("ERROR: File 'SuperStore_Sales_Dataset.csv' tidak ditemukan. Pastikan sudah diunggah.")
    exit()

df.columns = df.columns.str.replace(r'[+O6G3A1:R6]', '', regex=True).str.strip()
print("\nNama kolom telah dibersihkan.")

# 2. FILTERING DATA BERDASARKAN KATEGORI & SUB-KATEGORI
print("\nMelakukan filtering data...")
df_filtered = df[df['Category'] == 'Technology'].copy()
df_filtered = df_filtered[df_filtered['Sub-Category'] != 'Phones'].copy()
df_filtered['Profit_per_Unit'] = np.where(
    df_filtered['Quantity'] > 0,
    df_filtered['Profit'] / df_filtered['Quantity'],
    0
)
print(f"Jumlah baris setelah filter: {len(df_filtered)}")

# 3. PENYIAPAN DATA UNTUK REGRESI NUMERIK (Tanpa Waktu/Tempat)

# Daftar kolom yang TIDAK akan digunakan
columns_to_drop = [
    'Row ID', 'Order ID', 'Customer ID', 'Customer Name', 'Product ID', 'Product Name',
    'Order Date', 'Ship Date',
    'Country', 'City', 'State', 'Region',
    'Category', 'Returns', 'ind1', 'ind2'
]

df_model = df_filtered.drop(columns=columns_to_drop, errors='ignore').copy()

# Target: Kuantitas
target = 'Profit_per_Unit'

# Keluarkan target baru, serta 'Profit' dan 'Quantity' untuk menghindari kebocoran data
columns_to_exclude_from_X = [target, 'Profit', 'Quantity']

X = df_model.drop(columns=columns_to_exclude_from_X, errors='ignore')
y = df_model[target]

print(f"\nTarget Regresi: {target}")
print(f"Bentuk Fitur (X): {X.shape}")
print(f"Bentuk Target (y): {y.shape}")

# Daftar Fitur Numerik dan Kategorikal
categorical_features = ['Ship Mode', 'Segment', 'Sub-Category', 'Payment Mode']
numerical_features = ['Sales', 'Profit']

df_model_iloc = df_model[0:10]

print(df_model_iloc)